<?php

return [
    'class_namespace' => 'App\\Livewire',
    'view_path' => resource_path('views/livewire'),
    'layout' => 'layouts.app',
    'temporary_file_upload' => [
        'disk' => null,
        'rules' => null,
        'directory' => null,
        'middleware' => null,
        'preview_mimes' => [
            'png', 'gif', 'bmp', 'svg', 'wav', 'mp4',
            'mov', 'avi', 'wmv', 'mp3', 'm4a',
            'jpg', 'jpeg', 'mpga', 'webp', 'wma',
        ],
        'max_upload_time' => 5,
    ],
    'manifest_path' => null,
    'back_button_cache' => false,
    'render_on_redirect' => false,
    'asset_url' => null,
    'app_url' => null,
    'middleware_group' => 'web',
    'inject_assets' => true,
    'inject_morph_markers' => true,
    'back_button_cache' => false,
    'render_on_redirect' => false,
    'persist_scripts' => true,
    'inject_assets' => true,
    'inject_morph_markers' => true,
    'cache_components' => true,
    'cache_views' => true,
    'cache_queries' => true,
    'cache_rendered_views' => true,
    'cache_rendered_components' => true,
    'cache_rendered_queries' => true,
    'cache_rendered_scripts' => true,
    'cache_rendered_styles' => true,
    'cache_rendered_assets' => true,
    'cache_rendered_markers' => true,
    'cache_rendered_morphs' => true,
    'cache_rendered_events' => true,
    'cache_rendered_actions' => true,
    'cache_rendered_redirects' => true,
    'cache_rendered_errors' => true,
    'cache_rendered_validation' => true,
    'cache_rendered_validation_errors' => true,
    'cache_rendered_validation_messages' => true,
    'cache_rendered_validation_rules' => true,
    'cache_rendered_validation_attributes' => true,
    'cache_rendered_validation_custom' => true,
    'cache_rendered_validation_custom_messages' => true,
    'cache_rendered_validation_custom_rules' => true,
    'cache_rendered_validation_custom_attributes' => true,
    'cache_rendered_validation_custom_custom' => true,
    'cache_rendered_validation_custom_custom_messages' => true,
    'cache_rendered_validation_custom_custom_rules' => true,
    'cache_rendered_validation_custom_custom_attributes' => true,
];
